export const geoJSON = {
  type : "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.838365, 59.236914] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Botkyrka H\u00e5gelbyleden",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 24.98,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund Stockholm",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.10725,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63317244, 59.83171574],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund (Norr Malma)",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 9.23926,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sankt Eriksgatan",
        coordinates: null,
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 29.5445,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.634752, 59.2013399995282],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0114A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 12.3132,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.076799, 59.39929999953],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0108A",
        measurements_parameter: "O3",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 71.5,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9688665, 59.3667459] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan, Sundbyberg",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 15.1,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [16.178606, 58.590397] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Kungsgatan, Norrk\u00f6ping",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 6.3,
        measurements_lastupdated: "2022-05-25T21:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "(Folkungagatan tillf\u00e4lligt avst\u00e4ngd)",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: -99.0,
        measurements_lastupdated: "2018-04-04T17:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.057501, 59.3169399995293],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0022A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.25165,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.062386, 59.348618] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Valhallav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 25.8,
        measurements_lastupdated: "2022-05-25T21:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.07585555, 59.31462368],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Folkungagatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.5,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9995942, 59.3659396] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "R\u00e5sndav\u00e4gen, Solna",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 2.4,
        measurements_lastupdated: "2022-05-26T08:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.05862, 59.3411099995295],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0027A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 15.554,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63112, 59.832499999534],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0066A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 5.608,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.992711, 59.362291] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Solna R\u00e5sundav\u00e4gen",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.4,
        measurements_lastupdated: "2022-10-28T08:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.031951, 59.334351] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "St Eriksgatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 0.0,
        measurements_lastupdated: "2022-10-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.952473, 59.44575] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sollentuna Danderydsv\u00e4gen",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 11.4667,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04918, 59.3172199995292],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0003A",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 2.8013,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.00396061, 59.32551867],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Lilla Essingen (E4/E20)",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: -99.0,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.057501, 59.3169399995293],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0022A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.94566,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.301129, 57.637377] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "\u00d6sterv\u00e4g, Visby",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.6,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9688665, 59.3667459] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan, Sundbyberg",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 11.9,
        measurements_lastupdated: "2022-10-28T08:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "H\u00e4ggvik",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 4.9055,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.05428175, 59.34516113],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sveav\u00e4gen",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 16.5,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.019706, 59.363839] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "R\u00e5sundav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 15.4,
        measurements_lastupdated: "2022-10-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Lilla Essingen",
        coordinates: null,
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 0.0,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.07062632, 59.33635627],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Norrlandsgatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 24.4175,
        measurements_lastupdated: "2018-01-08T10:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.922358, 59.4435349995304],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0071A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 13.0025,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63112, 59.832499999534],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0066A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 1.6575,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund Stockholm",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 12.3366,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.0044, 59.3254999995293],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0087A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 22.575,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.05862, 59.3411099995295],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0027A",
        measurements_parameter: "CO",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 16.4495,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.05428175, 59.34516113],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sveav\u00e4gen",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 0.0,
        measurements_lastupdated: "2023-01-11T19:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9688665, 59.3667459] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan, Sundbyberg",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.6,
        measurements_lastupdated: "2022-10-28T08:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.00396061, 59.32551867],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Lilla Essingen (E4/E20)",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: -99.0,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.83833241, 59.23705806],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "H\u00e5gelbyleden Botkyrka",
        measurements_parameter: "NO2",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.63575,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.0044, 59.3254999995293],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0087A",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 898.163,
        measurements_lastupdated: "2020-10-22T07:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.035773, 59.338921] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sankt Eriksgatan",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 4.5,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.062386, 59.348618] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Valhallav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 2.1,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.992711, 59.362291] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Solna R\u00e5sundav\u00e4gen",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.26982,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [16.762106, 60.605031] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 21.3,
        measurements_lastupdated: "2022-10-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9995942, 59.3659396] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "R\u00e5sndav\u00e4gen, Solna",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 4.4,
        measurements_lastupdated: "2022-10-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.019706, 59.363839] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "R\u00e5sundav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 14.7,
        measurements_lastupdated: "2022-05-25T17:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund Norr Malma",
        coordinates: null,
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 2.47445,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.00388, 59.313251] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Skonertv\u00e4gen (E4/E20)",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 50.575,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.922494, 59.44358] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sollentuna H\u00e4ggvik (E4)",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 16.1175,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "E4/E20 Gr\u00f6ndal",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 19.175,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Danderydsv\u00e4gen Sollentuna",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 34.92,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.057501, 59.3169399995293],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0022A",
        measurements_parameter: "O3",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 69.7124,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.035773, 59.338921] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sankt Eriksgatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 5.1,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [16.762106, 60.605031] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 19.2,
        measurements_lastupdated: "2022-05-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "H\u00e4ggvik",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 17.2,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund Norr Malma",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 1.59,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04878744, 59.31713214],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Hornsgatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 10.6,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [16.178606, 58.590397] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Kungsgatan, Norrk\u00f6ping",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.0,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund Stockholm",
        coordinates: null,
        measurements_parameter: "O3",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 39.0449,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund Stockholm",
        coordinates: null,
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.1576,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04878744, 59.31713214],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Hornsgatan",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 4.6,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Lilla Essingen",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 9.98125,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Skonertv\u00e4gen",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.55275,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04878744, 59.31713214],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Hornsgatan",
        measurements_parameter: "O3",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 40.4725,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.0357015, 59.3387558] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "St Erikgsgatan",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.2,
        measurements_lastupdated: "2022-06-14T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund Norr Malma",
        coordinates: null,
        measurements_parameter: "O3",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 37.945,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.05862, 59.3411099995295],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0027A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 5.86504,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63112, 59.832499999534],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0066A",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.13825,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.07585555, 59.31462368],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Folkungagatan",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 12.5,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.019706, 59.363839] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "R\u00e5sundav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 10.9,
        measurements_lastupdated: "2022-05-26T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Uppsaka Kungsgatan",
        coordinates: null,
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 6.79204,
        measurements_lastupdated: "2021-04-07T10:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63317244, 59.83171574],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund (Norr Malma)",
        measurements_parameter: "O3",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 58.945,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.922358, 59.4435349995304],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0071A",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 2.65259,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [15.631343, 58.40878] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Hamngatan, Link\u00f6ping",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.4,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund Norr Malma",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.82425,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63317244, 59.83171574],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund (Norr Malma)",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 6.04278,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04918, 59.3172199995292],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0003A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 11.255,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.301129, 57.637377] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "\u00d6sterv\u00e4g, Visby",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 9.0,
        measurements_lastupdated: "2022-05-25T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.031951, 59.334351] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "St Eriksgatan",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 13.9,
        measurements_lastupdated: "2022-05-25T21:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.00388, 59.313251] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Skonertv\u00e4gen (E4/E20)",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 54.305,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.621084, 59.1981199995282],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0072A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 44.7033,
        measurements_lastupdated: "2023-05-30T17:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund Norr Malma",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 1.59,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.057991, 59.315891] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund (Stockholm)",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 13.8925,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sankt Eriksgatan",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 44.94,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "(Folkungagatan tillf\u00e4lligt avst\u00e4ngd)",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: -99.0,
        measurements_lastupdated: "2018-04-04T17:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04918, 59.3172199995292],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0003A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 12.3715,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.035773, 59.338921] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sankt Eriksgatan",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 13.1,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.952473, 59.44575] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sollentuna Danderydsv\u00e4gen",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 22.6675,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.057991, 59.315891] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund (Stockholm)",
        measurements_parameter: "O3",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 52.2301,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.057991, 59.315891] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund (Stockholm)",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 8.52963,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.04878744, 59.31713214],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Hornsgatan",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 21.9,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.05428175, 59.34516113],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sveav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 7.5,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.992711, 59.362291] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Solna R\u00e5sundav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 14.925,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "E4/E20 Gr\u00f6ndal",
        coordinates: null,
        measurements_parameter: "PM10",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 32.61,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9688665, 59.3667459] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan, Sundbyberg",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 6.8,
        measurements_lastupdated: "2022-10-28T08:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.07062632, 59.33635627],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Norrlandsgatan",
        measurements_parameter: "PM10",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 13.5918,
        measurements_lastupdated: "2018-01-08T10:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.922358, 59.4435349995304],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0071A",
        measurements_parameter: "NO2",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 20.0525,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [17.621084, 59.1981199995282],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0072A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 18.7163,
        measurements_lastupdated: "2023-05-30T17:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.0357015, 59.3387558] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "St Erikgsgatan",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 0.0,
        measurements_lastupdated: "2022-10-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [15.631343, 58.40878] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Hamngatan, Link\u00f6ping",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 6.1,
        measurements_lastupdated: "2022-05-25T21:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Skonertv\u00e4gen",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 9.30675,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.057991, 59.315891] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Urban bakgrund (Stockholm)",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 10.6975,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.0044, 59.3254999995293],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0087A",
        measurements_parameter: "PM10",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 34.6501,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63112, 59.832499999534],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "SE0066A",
        measurements_parameter: "O3",
        measurements_sourcename: "EEA Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 67.6226,
        measurements_lastupdated: "2023-05-31T06:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9688665, 59.3667459] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan, Sundbyberg",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 14.6,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.9688665, 59.3667459] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Tulegatan, Sundbyberg",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 4.0,
        measurements_lastupdated: "2023-05-31T02:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.0636322, 59.4081664] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Danderydsv\u00e4gen",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 6.395,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.63317244, 59.83171574],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Regional bakgrund (Norr Malma)",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 2.03825,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [17.922494, 59.44358] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sollentuna H\u00e4ggvik (E4)",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 12.3525,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.0636322, 59.4081664] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Danderydsv\u00e4gen",
        measurements_parameter: "PM2.5",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 3.8,
        measurements_lastupdated: "2022-10-25T22:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [18.019706, 59.363839] },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "R\u00e5sundav\u00e4gen",
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 14.5,
        measurements_lastupdated: "2022-05-25T21:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Lilla Essingen",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 13.265,
        measurements_lastupdated: "2021-07-20T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [18.00396061, 59.32551867],
      },
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Lilla Essingen (E4/E20)",
        measurements_parameter: "PM10",
        measurements_sourcename: "Stockholm",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: -99.0,
        measurements_lastupdated: "2020-12-11T15:00:00+01:00",
        country_name_en: "Sweden",
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        country: "SE",
        city: "Stockholm",
        location: "Sankt Eriksgatan",
        coordinates: null,
        measurements_parameter: "NO2",
        measurements_sourcename: "Sweden",
        measurements_unit: "\u00b5g/m\u00b3",
        measurements_value: 17.6875,
        measurements_lastupdated: "2018-10-13T23:00:00+02:00",
        country_name_en: "Sweden",
      },
    },
  ],
}
